# Linux uses the shared libraries from the same pinned llama.cpp release.
find_library(GGML_BASE_LIBRARY NAMES ggml-base PATHS "${GGML_DIST}" NO_DEFAULT_PATH REQUIRED)
find_library(GGML_LIBRARY NAMES ggml PATHS "${GGML_DIST}" NO_DEFAULT_PATH REQUIRED)
find_package(Threads REQUIRED)
set(CMAKE_BUILD_RPATH "${GGML_DIST}")
set(CMAKE_INSTALL_RPATH "$ORIGIN")
add_library(ggml-xdna SHARED src/ggml-xdna.cpp src/xdna-ref.cpp src/xdna-platform.cpp include/ggml-xdna.h)
target_include_directories(ggml-xdna PRIVATE include "${GGML_HEADERS}/include" "${GGML_HEADERS}/src")
target_compile_definitions(ggml-xdna PRIVATE GGML_SHARED GGML_BACKEND_SHARED GGML_BACKEND_BUILD GGML_BACKEND_DL)
target_link_libraries(ggml-xdna PRIVATE "${GGML_BASE_LIBRARY}" "${GGML_LIBRARY}" Threads::Threads ${CMAKE_DL_LIBS})
if(GGML_XDNA_NPU)
    find_path(XRT_INCLUDE_DIR xrt/xrt_device.h HINTS /usr/include /opt/xilinx/xrt/include REQUIRED)
    find_library(XRT_COREUTIL NAMES xrt_coreutil HINTS /usr/lib/x86_64-linux-gnu /opt/xilinx/xrt/lib REQUIRED)
    target_sources(ggml-xdna PRIVATE src/xdna-npu.cpp src/xdna-exec.cpp src/npu/npu_bfp16.cpp src/npu/bfp16_pack.cpp src/npu/bfp16_insts.cpp vendor/xrt-shim/xrt_shim.cpp)
    target_include_directories(ggml-xdna PRIVATE src/npu vendor/xrt-shim "${XRT_INCLUDE_DIR}")
    target_compile_definitions(ggml-xdna PRIVATE XDNA_HAVE_NPU)
    target_compile_options(ggml-xdna PRIVATE -mavx2)
    target_link_libraries(ggml-xdna PRIVATE "${XRT_COREUTIL}")
endif()
set(XDNA_XCLBIN "${CMAKE_SOURCE_DIR}/kernels/bfp16_gemm/prebuilt/bfp16_gemm.xclbin")
add_custom_command(TARGET ggml-xdna POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E copy_if_different $<TARGET_FILE:ggml-xdna> "${GGML_DIST}"
    COMMAND ${CMAKE_COMMAND} -E copy_if_different "${XDNA_XCLBIN}" "${GGML_DIST}"
    COMMAND ${CMAKE_COMMAND} -E copy_if_different "${XDNA_XCLBIN}" $<TARGET_FILE_DIR:ggml-xdna>)
enable_testing()
add_test(NAME linux-launcher COMMAND bash "${CMAKE_SOURCE_DIR}/tests/test-linux-launcher.sh")
set_tests_properties(linux-launcher PROPERTIES LABELS host)
foreach(t test-mul-mat test-dispatch-gate test-memory-budget test-safe-start)
    add_executable(${t} tests/${t}.cpp)
    target_include_directories(${t} PRIVATE "${GGML_HEADERS}/include")
    target_compile_definitions(${t} PRIVATE GGML_SHARED GGML_BACKEND_SHARED)
    target_link_libraries(${t} PRIVATE "${GGML_BASE_LIBRARY}" "${GGML_LIBRARY}")
    add_custom_command(TARGET ${t} POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy_if_different $<TARGET_FILE:${t}> "${GGML_DIST}")
endforeach()
add_executable(test-insts-gen tests/test-insts-gen.cpp src/npu/bfp16_insts.cpp)
target_include_directories(test-insts-gen PRIVATE src/npu)
target_compile_definitions(test-insts-gen PRIVATE XDNA_INSTS_DIR="${CMAKE_CURRENT_SOURCE_DIR}/tests/insts")
add_executable(test-bfp16-pack tests/test-bfp16-pack.cpp src/npu/bfp16_pack.cpp)
target_include_directories(test-bfp16-pack PRIVATE src/npu)
target_compile_options(test-bfp16-pack PRIVATE -mavx2)
set(XDNA_ENV "GGML_BACKEND_PATH=${GGML_DIST}/libggml-xdna.so" "GGML_XDNA_KERNELS=")
add_test(NAME insts-gen COMMAND test-insts-gen)
add_test(NAME bfp16-pack COMMAND test-bfp16-pack)
add_test(NAME safe-start COMMAND "${GGML_DIST}/test-safe-start")
add_test(NAME safe-start-no-driver COMMAND "${GGML_DIST}/test-safe-start" --no-driver)
foreach(t dispatch-gate mul-mat)
    add_test(NAME ${t}-host COMMAND "${GGML_DIST}/test-${t}")
    add_test(NAME ${t}-npu COMMAND "${GGML_DIST}/test-${t}")
    set_tests_properties(${t}-host PROPERTIES LABELS host ENVIRONMENT "${XDNA_ENV};GGML_XDNA_HOST_ONLY=1")
    set_tests_properties(${t}-npu PROPERTIES LABELS npu ENVIRONMENT "${XDNA_ENV};GGML_XDNA_HOST_ONLY=")
endforeach()
add_test(NAME mul-mat-npu-nan COMMAND "${GGML_DIST}/test-mul-mat")
set_tests_properties(mul-mat-npu-nan PROPERTIES LABELS npu ENVIRONMENT "${XDNA_ENV};GGML_XDNA_HOST_ONLY=;GGML_XDNA_NAN_AFTER=0")
foreach(mode host npu)
    add_test(NAME memory-budget-${mode} COMMAND "${GGML_DIST}/test-memory-budget")
endforeach()
set_tests_properties(memory-budget-host PROPERTIES LABELS host ENVIRONMENT "${XDNA_ENV};GGML_XDNA_MAX_COPY_GB=0.05;GGML_XDNA_HOST_ONLY=1")
set_tests_properties(memory-budget-npu PROPERTIES LABELS npu ENVIRONMENT "${XDNA_ENV};GGML_XDNA_MAX_COPY_GB=0.05;GGML_XDNA_HOST_ONLY=")
set_tests_properties(insts-gen bfp16-pack safe-start PROPERTIES LABELS host ENVIRONMENT "${XDNA_ENV}")
set_tests_properties(safe-start-no-driver PROPERTIES LABELS nodriver ENVIRONMENT "${XDNA_ENV}")
